# Generated by Django 4.2.3 on 2023-11-21 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Reservas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField()),
                ('horario', models.CharField(choices=[[0, '8:30-9:00'], [1, '9:00-9:30'], [2, '9:30-10:00'], [3, '10:00-10:30'], [4, '10:30-11:00'], [5, '11:00-11:30'], [6, '11:30-12:00']], max_length=100)),
                ('examinadorA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reservas.examinador', verbose_name='Examinador')),
            ],
        ),
    ]
