# Generated by Django 4.2.3 on 2023-11-24 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Reservas', '0002_agenda'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Examinador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reservas.examinador', verbose_name='Examinador')),
                ('Horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reservas.agenda', verbose_name='Horario')),
            ],
        ),
    ]
