# Generated by Django 4.2.3 on 2023-11-26 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Reservas', '0005_remove_agenda_examinadora_remove_examen_examinadore_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenda',
            name='Tipo_reserva',
        ),
        migrations.RemoveField(
            model_name='examen',
            name='examinador',
        ),
        migrations.AddField(
            model_name='agenda',
            name='examinadorA',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Reservas.examinador', verbose_name='Examinador'),
        ),
        migrations.AddField(
            model_name='examen',
            name='examinadorE',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Reservas.examinador', verbose_name='Examinador'),
        ),
    ]
