# Generated by Django 4.2.3 on 2023-11-27 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Reservas', '0006_remove_agenda_tipo_reserva_remove_examen_examinador_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenda',
            name='examinadorA',
        ),
        migrations.AddField(
            model_name='agenda',
            name='tipo_evaluacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Reservas.examen', verbose_name='Tipo de reserva'),
        ),
    ]
