# Generated by Django 4.2.3 on 2023-11-27 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Reservas', '0007_remove_agenda_examinadora_agenda_tipo_evaluacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='rut',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='tipo_evaluacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Reservas.examen', verbose_name='Tipo de reserva'),
        ),
    ]
