# Generated by Django 4.2.3 on 2023-11-27 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservas', '0008_agenda_rut_alter_agenda_tipo_evaluacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='examen',
            name='tipo_vehiculo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='horario',
            field=models.CharField(choices=[['0', 'auto'], ['1', 'motocicleta'], ['2', 'camion '], ['3', 'maquinaria pesada '], ['4', 'transporte escolar ']], max_length=100),
        ),
    ]
