# Generated by Django 4.2.3 on 2023-11-27 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservas', '0011_remove_examen_tipo_vehiculo_agenda_tipo_vehiculo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examen',
            name='examinadorE',
        ),
        migrations.AddField(
            model_name='examen',
            name='descripcion_examen',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Describe Algo Del Examen'),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='tipo_vehiculo',
            field=models.CharField(blank=True, choices=[['0', 'auto'], ['1', 'motocicleta'], ['2', 'camion '], ['3', 'maquinaria pesada '], ['4', 'transporte escolar '], ['5', 'otro ']], max_length=100, null=True),
        ),
    ]
