# Generated by Django 4.2.3 on 2023-11-27 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservas', '0012_remove_examen_examinadore_examen_descripcion_examen_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenda',
            name='tipo_vehiculo',
        ),
        migrations.AddField(
            model_name='examen',
            name='tipo_vehiculo',
            field=models.CharField(blank=True, choices=[['0', 'auto'], ['1', 'motocicleta'], ['2', 'camion '], ['3', 'maquinaria pesada '], ['4', 'transporte escolar '], ['5', 'otro ']], max_length=100, null=True),
        ),
    ]
